version: 2

sources:
  - name: raw
    description: "Raw data ingested from Kafka consumer into PostgreSQL"
    database: ecommerce
    schema: public
    tables:
      - name: raw_orders
        description: "Raw order events streamed from Kafka. Contains one row per product per order."
        columns:
          - name: id
            description: "Auto-incrementing primary key"
            tests:
              - unique
              - not_null
          - name: order_id
            description: "Order identifier from source system"
            tests:
              - not_null
          - name: event_timestamp
            description: "Timestamp when the order event was created"
            tests:
              - not_null

models:
  - name: stg_orders
    description: "Staging view of raw order data. Pass-through layer with minimal transformations for downstream consumption."
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
      - name: customer_city
        description: "City where the customer is located"
      - name: customer_state
        description: "Brazilian state code where customer is located (e.g., SP, RJ, MG)"
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - not_null
      - name: product_category
        description: "Product category name (some may be in Portuguese)"
      - name: price
        description: "Price of the individual product in Brazilian Real (BRL)"
        tests:
          - not_null
      - name: freight_value
        description: "Shipping cost for this product in BRL"
        tests:
          - not_null
      - name: payment_type
        description: "Payment method used (e.g., credit_card, boleto, voucher)"
      - name: payment_value
        description: "Amount paid for this product in BRL"
        tests:
          - not_null
      - name: order_status
        description: "Current status of the order (e.g., delivered, shipped, canceled)"
      - name: event_timestamp
        description: "Timestamp when this order event occurred"
        tests:
          - not_null
      - name: ingested_at
        description: "Timestamp when this record was ingested into the database"
        tests:
          - not_null
